### ISSUE TITLE
Autofill code

### ISSUE THREAD

**Issue by ncampuzano** [shixiaoquan/react-native-sms-verifycode#12]
Hello! 
I'm  trying to autofill code on boxes, there is a way to do this? (Passing initial value to component)

**Comment by shixiaoquan** [comment]
@ncampuzano 
This feature has been added, 
please pass in a props ‘ initialCodes’ when initializing

**Comment by shixiaoquan** [comment]
Please use the latest version

**Comment by ncampuzano** [comment]
Thank you man! Good sms verify code 👍

**Comment by ncampuzano** [comment]
I found that when I pass initialCodes the onInputCompleted event isn't fired.

**Comment by gdmec07140512** [comment]
为什么这个值无法更改？
