### ISSUE TITLE
the keyboard and password box can not appear at the same time

### ISSUE THREAD

**Issue by RowgerGo** [shixiaoquan/react-native-sms-verifycode#2]
When I use SMSVerifyCode, the keyboard and password box can not appear at the same time, must click the password box to appear the keyboard, I think the keyboard and password box will appear at the same time, the user experience will be better

**Comment by shixiaoquan** [comment]
Two APIs(blur and focus) have been added for hiding and displaying the keyboard
See readme for details
https://github.com/shixiaoquan/react-native-sms-verifycode#apis
