### ISSUE TITLE
Container样式的设置

### ISSUE THREAD

**Issue by willsame** [shixiaoquan/react-native-sms-verifycode#4]
Container样式的可以设置为这种么？
![goolgle](https://user-images.githubusercontent.com/19715001/44080331-4edc23a8-9fde-11e8-9620-981e24635d6e.jpg)
)

**Comment by shixiaoquan** [comment]
我没写这个api，我晚上加一下🐥，好了告诉你

**Comment by soloFZZ** [comment]
你好请问这种样式现在有了吗

**Comment by shixiaoquan** [comment]
@willsame @soloFZZ  好了，支持了。使用方法在 example 里面有， 设置codeViewStyle 的时候要注意，因为默认是有边框和 radius 的，如果只要下面的请边框，请把其他三个设置为 width:0，并把 radius 设置为 0。

**Comment by soloFZZ** [comment]
好的，非常感谢

**Comment by shixiaoquan** [comment]
@soloFZZ  不客气

**Comment by willsame** [comment]
@shixiaoquan 感谢感谢

**Comment by shixiaoquan** [comment]
@willsame  不客气

**Comment by wentianl20** [comment]
没找到设置方法啊
