### ISSUE TITLE
每个输入框margin自己设置

### ISSUE THREAD

**Issue by soloFZZ** [shixiaoquan/react-native-sms-verifycode#5]
你好，我想问一下，我看你的代码写的应该是每个输入框之间的margin距离是自动计算的，这样会导致我无法自己设置每个的间距，并且再更改codeViewWidth之后样式会乱掉，给containerStyle设置justifyContent的任何值都是一个效果。 
 能否不去计算并且设置margin的值从而我自己使用justifyContent去控制距离   目前
![image](https://user-images.githubusercontent.com/22954173/44196457-93073e00-a16e-11e8-8a52-26733dc91dd6.png)

![image](https://user-images.githubusercontent.com/22954173/44196499-b16d3980-a16e-11e8-9d26-6c6cbe9e1647.png)

**Comment by soloFZZ** [comment]
设置之后样式已经乱了  我尝试注释掉你的设置marginLeft和marginRight 的代码之后 就可以了
![image](https://user-images.githubusercontent.com/22954173/44196647-12950d00-a16f-11e8-9478-b4744d535015.png)
左右的边距是我加的container的padding

**Comment by shixiaoquan** [comment]
新版本的思路是，输入框的 宽高 都可以设置，然后 container的上下左右边距 都可以设置， 但是每个文本框的之间的距离，还是相同的，我觉得正常情况下，应该都是相等的，如果你有特殊的需求？可以咱俩再商量下怎么设计。按照目前的思路只能是这样了

**Comment by soloFZZ** [comment]
好的，万分感谢 明白你的意思了，我的并非特殊需求已经弄哈了
