### ISSUE TITLE
被选中的input边框色值没有更改

### ISSUE THREAD

**Issue by soloFZZ** [shixiaoquan/react-native-sms-verifycode#7]
设置的focusedCodeViewBorderColor属性无效
![image](https://user-images.githubusercontent.com/22954173/44201632-4c204500-a17c-11e8-903c-0549c359fd7c.png)
![image](https://user-images.githubusercontent.com/22954173/44201664-6823e680-a17c-11e8-94d0-d4abdede5928.png)
直接复制你文档上的demo的代码也无focus的色值改变

**Comment by shixiaoquan** [comment]
该bug 已修复

**Comment by willsame** [comment]
@shixiaoquan 设置了好像还是没有效果
