### ISSUE TITLE
验证码框可选是否页面打开获得焦点

### ISSUE THREAD

**Issue by soloFZZ** [shixiaoquan/react-native-sms-verifycode#8]
你好，我发现目前的是页面刚打开就会自动获得焦点，  作为建议是否可以设置页面打开的时候是否获得焦点  类似我这种需求是不需要页面刚打开的时候focus的
![image](https://user-images.githubusercontent.com/22954173/44256451-cb288280-a23b-11e8-805b-9c0d7ffb3458.png)

**Comment by shixiaoquan** [comment]
最新版本已经可以通过 autoFocus 设置默认是否获取焦点 ，弹出键盘
but
并不完美，还有一个问题，暂时还没解决
在组件 获取焦点的情况下，按 home 键回到桌面，再次进入 App 时，选中的 codeView 的边框的特殊颜色会消失，其它情况下，暂时没发现问题
我在找解决方案，如果你有思路欢迎告诉我🙃

**Comment by shixiaoquan** [comment]
这个问题 ，目前只出现在Android 上，iOS 是完美的

**Comment by shixiaoquan** [comment]
@soloFZZ  问题已经解决了，请使用最新版本
