### ISSUE TITLE
在验证码框高亮异常

### ISSUE THREAD

**Issue by soloFZZ** [shixiaoquan/react-native-sms-verifycode#9]
在验证码框失去焦点验证码框的高亮依旧存在
![image](https://user-images.githubusercontent.com/22954173/44256835-ec3da300-a23c-11e8-932a-d892f88bb148.png)
![image](https://user-images.githubusercontent.com/22954173/44256921-20b15f00-a23d-11e8-9519-c4d3d11a68f3.png)

**Comment by soloFZZ** [comment]
1图是我让第一个文本框获得焦点的情况
2图是我点击空白区域隐验证码框失去焦点键盘消失情况

**Comment by shixiaoquan** [comment]
已解决，请更新最新版本

**Comment by soloFZZ** [comment]
你好， 第一个问题没有解决   就是在第一个input框获得焦点的时候 下面的也给高亮了。

**Comment by soloFZZ** [comment]
为什么图一上的 我第一个input获得焦点的时候也会触发你组件里面的代码执行![image](https://user-images.githubusercontent.com/22954173/44713668-31d45880-aae6-11e8-90c5-baa9ecbf60a6.png)
请问你这个是通过什么监听的呢

**Comment by shixiaoquan** [comment]
@soloFZZ  看下这个图 
https://github.com/shixiaoquan/react-native-sms-verifycode/blob/master/example/android.gif
这是我这边的效果，OK的

**Comment by soloFZZ** [comment]
这样的效果是好着的  你可以尝试一下  给页面上再来个input框  然后当上面那个input框获得焦点的时候如下图：
![image](https://user-images.githubusercontent.com/22954173/44721700-5425a080-aafd-11e8-9289-fd5b8641f6f3.png)
我的光标焦点是在上面我的input上

**Comment by soloFZZ** [comment]
你说的‘监听了 keyboard的 show hide 事件’   那就是应该因为这个原因了   因为我键盘的show是另一个input框获取焦点的原因了。。

**Comment by willsame** [comment]
@soloFZZ 你好，能贴一下你的验证码的样式么，我的跟你是一样的，发现我无论怎么设置，输入的时候都没有高亮，灰常感谢。

**Comment by soloFZZ** [comment]
@willsame  
![image](https://user-images.githubusercontent.com/22954173/44825829-e97c7e00-ac3e-11e8-8aa1-7616fb3a32a9.png)
![image](https://user-images.githubusercontent.com/22954173/44825844-fbf6b780-ac3e-11e8-9190-c68ab7d92160.png)


如果你搭建的是ios 用xcode起的并且选择机型是iPhone se 的话   你需要在上面菜单栏点击 Hardware->Keyboard -> connect hardware keyboard勾选去掉  这个时候点击验证码才回在模拟器里面弹出键盘 高亮才能出现，
或者你直接用xcode  链接真机调试就可以知道是不是你代码问题了

**Comment by soloFZZ** [comment]
@shixiaoquan   能否根据判断当前获取焦点的是哪个input从而避免我上面所描述的那种问题出现 谢谢

**Comment by shixiaoquan** [comment]
已修复
